config/routes.rb
Rails.application.routes.draw do
  resources :cocktail_ingredients
  resources :ingredients
  resources :bar_cocktails
  resources :bars
  resources :cocktails

  # (edit)
  # create -> redirects to add_amounts -> patches, then redirects to show
  get "cocktails/:id/add_amounts", to: "cocktails#add_amounts", as: "add_amounts"
  #get "cocktails/:id/add_amounts", to: "cocktails#add_amounts", as "add_amounts"
  # patch "cocktails/:id/"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord

    has_many :bar_cocktails
    has_many :cocktails, through: :bar_cocktails
end

app/models/bar_cocktail.rb
class BarCocktail < ApplicationRecord
    belongs_to :bar
    belongs_to :cocktail 
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

    has_many :bar_cocktails
    has_many :bars, through: :bar_cocktails

    has_many :cocktail_ingredients
    has_many :ingredients, through: :cocktail_ingredients
    
end

app/models/cocktail_ingredient.rb
class CocktailIngredient < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

    has_many :cocktail_ingredients
    has_many :cocktails, through: :cocktail_ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bar_cocktails_controller.rb
class BarCocktailsController < ApplicationController
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
    
    before_action :find_bar, only: [:show, :edit, :update, :destroy]

    def index
        @bars = Bar.all
    end
    
    def show
    end

    def edit
    end
    
    def update
        @bar.update(bar_params)
        redirect_to bar_path(@bar)
    end

    def new
        @bar = Bar.new
    end

    def create
        @bar = Bar.new(bar_params)
        @bar.save
        redirect_to bars_path(@bar)
    end
    
    def destroy
        Bar.destroy(params[:id])
        redirect_to bars_path
    end

    private 

    def find_bar
        @bar = Bar.find(params[:id])
    end

    def bar_params
        params.require(:bar).permit(:name, :location, cocktail_ids:[])
    end
end

app/controllers/cocktail_ingredients_controller.rb
class CocktailIngredientsController < ApplicationController

    def update
        cocktail_ingredient = CocktailIngredient.find(params[:id])
        cocktail_ingredient.update(ci_params)
        redirect_to(cocktail_path(cocktail_ingredient.cocktail_id))
    end

    private 

    def ci_params
        params.require(:cocktail_ingredient).permit(:cocktail_id, :ingredient_id, :quantity)
    end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

    before_action :find_cocktail, only: [:show, :edit, :update, :destroy, :add_amounts] #makes it so at the beginning of all four of these methods, find_cocktail is ran (see private method)

    def index
        @cocktails = Cocktail.all
    end
    
    def show
        #find_cocktail does the work for us - don't have to write any code here!
    end

    def edit
    end
    
    def update
        @cocktail.update(cocktail_params) #see our private method
        redirect_to(add_amounts_path(@cocktail))
    end

    def new
        @cocktail = Cocktail.new
    end

    def create
        cocktail = Cocktail.create(cocktail_params) #see our private method
        redirect_to(add_amounts_path(cocktail))
    end

    def add_amounts
        @current_cocktail = {cocktail: @cocktail}
    end

    def update_amounts
        @cocktail.update(cocktail_params)
        redirect_to(cocktail_path(@cocktail))
    end
    
    def destroy
        @cocktail.destroy
        redirect_to(cocktails_path)
    end

    private 

    def cocktail_params
        params.require(:cocktail).permit(:name, :price, :description, bar_ids:[], ingredient_ids:[])
    end

    def find_cocktail
        @cocktail = Cocktail.find(params[:id])
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    before_action :find_ingredients, only: [:show, :edit, :update, :destroy]

    def index
        @ingredients = Ingredient.all
    end
    
    def show
    end

    def edit
    end
    
    def update
        @ingredient.update(ingredient_params)
        redirect_to ingredient_path(@ingredient)
    end

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)
        @ingredient.save
        redirect_to ingredients_path(@ingredient)
    end
    
    def destroy
        Ingredient.destroy(params[:id])
        redirect_to ingredients_path
    end

    private 

    def find_ingredients
        @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
       params.require(:ingredient).permit(:name, :quantity, :measurement, cocktail_ids:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bar_cocktails_helper.rb
module BarCocktailsHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/cocktail_ingredients_helper.rb
module CocktailIngredientsHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/bars/edit.html.erb
<h1>Re-bar</h1>

<%= form_for @bar do |f| %>
<%= f.label "Bar Name" %>:
<%= f.text_field :name %><br/><br/>

<%= f.label "Bar Location" %>:
<%= f.text_field :location %><br/><br/>
<%= f.label "Cocktails" %>
<%= f.collection_select :cocktail_ids, Cocktail.all, :id, :name, {}, {multiple: true} %><br><br>
<%= f.submit "Edit Bar Info" %>
<% end %>

app/views/bars/index.html.erb
<h1>Cool Bars Are Listed Here</h1>

<ul>
    <% @bars.each do |bar| %>
    <li>
        <%= link_to bar.name, bar_path(bar) %>
    </li>
    <% end %>
</ul>

<%= button_to "Add a bar", new_bar_path, method: "get" %><br><br>

<%= button_to "Go To Cocktails", cocktails_path, method: "get" %>

app/views/bars/new.html.erb
<h1>Setting the Bar</h1>

<%= form_for @bar do |f| %>
<%= f.label "Bar Name" %>:
<%= f.text_field :name %><br/><br/>

<%= f.label "Bar Location" %>:
<%= f.text_field :location %><br/><br/>

<%= f.label "Pick Your Poison(s)" %><br><br>
<%= f.collection_select :cocktail_ids, Cocktail.all, :id, :name, {}, {multiple: true} %><br><br>

<%= f.submit "Add New Bar" %>


<% end %>

app/views/bars/show.html.erb
<h1> <%= @bar.name %> </h1>

<h3><%= @bar.location %></h3>


<div>Cocktail Menu</div>

<ul>
    <% @bar.cocktails.each do |cocktail| %>
        <li>
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
        </li>
    <% end %>
</ul>





<%= button_to("Update Bar Info", edit_bar_path, method: "get") %><br><br>

<%= link_to("Back to All Bars", bars_path) %>

app/views/cocktails/add_amounts.html.erb
<h1>Specify Amounts for <%= @cocktail.name %></h1>

<% @cocktail.cocktail_ingredients.each do |ci| %>
    <%= form_for(ci) do |f| %>
        <%= f.label "Quantity of " +  ci.ingredient.name %>
        <%= f.number_field :quantity  %>
        <%= f.submit "Submit Ingredient Amounts" %>
    <% end %>
    <br>
<% end %>

app/views/cocktails/edit.html.erb
<h1> Edit The <%= @cocktail.name %></h1>
<%= form_for(@cocktail) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :price %>
    <%= f.number_field :price, step: :any %>
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br>
    <%= f.label :bars %>
    <%= f.collection_check_boxes :bar_ids, Bar.all, :id, :name %>
    <br>
    <br>
    <%= f.label :ingredients %>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>

     <!-- this is some magic, idk -->
    <!-- #this is basically gonna be a mix of new, edit, & destroy bar_cocktail all at the same time. should we make a method for it inside of cocktail.rb? not sure... -->
    <br>
    <%= f.submit("Submit Changes") %>
<% end %>

app/views/cocktails/index.html.erb
<h1>All Cocktails</h1>
<ul><% @cocktails.each do |cocktail| %>
    <li><%= link_to(cocktail.name, cocktail_path(cocktail)) %></li>
<% end %></ul>
<br>
<%= button_to("Create Cocktail", new_cocktail_path, method: "get") %><br><br>

<%= button_to "Go To Bars", bars_path, method: "get" %>

app/views/cocktails/new.html.erb
<h1>Make a Cocktail!</h1>
<%= form_for(@cocktail) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :price %>
    <%= f.number_field :price, step: :any %>
    <br>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <br>

    <%= f.label :bars %>
    <%= f.collection_check_boxes :bar_ids, Bar.all, :id, :name %><br>
    <br>
    <br>
    <%= f.label :ingredients %>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>

    <%= f.submit("Create Cocktail") %>
<% end %>

app/views/cocktails/show.html.erb
<h1>The <%= @cocktail.name %></h1>

<% if @cocktail.description %>
    <p><%= @cocktail.description %></p>
<% else %>
    <p>No description given.</p>
<% end %>

<p>Price: $<%= @cocktail.price %></p>

<ul>
    <% @cocktail.cocktail_ingredients.each do |ci|%>
    <li>
        <%= ci.quantity %>
        <%= ci.ingredient.measurement %>
        <%= ci.ingredient.name %>

    </li>
    <% end %>
</ul>

<h3>Bars:</h3>
<% if @cocktail.bars != nil && @cocktail.bars != [] %>
    <ul><% @cocktail.bars.each do |bar| %>
        <li><%= link_to(bar.name, bar_path(bar)) %></li>
    <% end %></ul>
<% else %>
    <p>Add a bar to this cocktail, ya dummy!</p>
<% end %>

<br>
<%= button_to("Edit Cocktail", edit_cocktail_path(@cocktail), method: "get") %>
<br>
<%= link_to("Back to All Cocktails", cocktails_path) %>

app/views/ingredients/index.html.erb
<h1>All the Fixins</h1>
<ul>
    <% @ingredients.each do |ingredient| %>
    <li>
        <%= link_to ingredient.name, ingredient_path(ingredient) %>
    </li>    
    <% end %>
</ul>

<%= link_to "Add Another Ingredient", new_ingredient_path %>

app/views/ingredients/new.html.erb
<%= form_for @ingredient do |f| %>
<%= f.label "name" %>
<%= f.text_field :name %>
<%= f.label "measurement" %>
<%= f.text_field :measurement %>
<%= f.submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<ul>
    <li>
    <%= @ingredient.measurement%>
    </li>
<ul>

<%= link_to "Edit Ingredient", edit_ingredient_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>